import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navigation/Navbar";

const inter = Inter({ subsets: ["latin"] });

// Indicate that this layout should be rendered dynamically on each request
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Task Management System",
  description: "Generated by Task Management System Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="h-full flex-grow bg-light-primary">
          {children}
        </div>
      </body>
    </html>
  );
}
